#!/usr/bin/env ruby

dir = "/tmp/fakemail"
Dir.mkdir(dir) unless File.exists?(dir)

headers = '' ; body = ''
$stdin.each_line { |l| headers << l ; break if l.strip.length == 0 }
$stdin.each_line { |l| body << l }

format = body.match(/html/i) ? "html" : "txt"
filename = Time.now.to_i

File.open("#{dir}/#{filename}_headers.txt", "w")  { |f| f.write(headers) }
File.open("#{dir}/#{filename}.#{format}", "w")    { |f| f.write(body) }